config/routes.rb
TechPlaces::Application.routes.draw do
  root :to => 'welcome#index'
  get "about", to: 'welcome#about'
  get "index", to: 'welcome#index'

  resources :contacts, only: [:new, :create]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :body, :email, :name

  validates :name, :email, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to index_path, notice: 'Message sent' }
      else
        format.html { render action: "new" }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/new.html.erb
 <!--[if IE]><script>
      $(document).ready(function() {

          $("#form_wrap").addClass('hide');

      })

  </script><![endif]-->

 <% if @contact.errors.any? %>
     <div id="error_explanation" style="margin-left: 30%; margin-top: 20px;">
       <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this car from being saved:</h2>

       <ul>
         <% @contact.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
 <% end %>

 <div class="clear"></div>

 <div id="wrap">
  <h1>Send a message</h1>
  <div id='form_wrap'>
      <%= form_for @contact do |f|%>
          <label for="name">Name: </label>
          <%= f.text_field :name %>
          <label for="email">Email: </label>
          <%= f.text_field :email %>
          <label for="email">Your Message : </label>
          <%= f.text_area :body %>
          <%= f.submit "Now, I send, thanks!" %>
    <%- end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechPlaces</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "styles" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render partial: 'shared/header' %>
<%= render partial: 'shared/menu' %>
<% if flash[:notice] -%>
    <p class='notice'><%=h flash[:notice] %></p>
<% end -%>
<%= yield %>
<%= render partial: 'shared/footer' %>
</body>
</html>

app/views/shared/_footer.html.erb
<div id="fotterBottomContainer">
  <div id="fotterBottomOuter">
    <p>Copyright © 2013 TechsPlace. All rights reserved.</p>
    <a href="#" class="top">top</a>
    <ul class="manue">
      <li><%= link_to 'Home', index_path %></li>
      <li><%= link_to 'Portfolio', "#" %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', new_contact_path %></li>

    </ul>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
</div>

app/views/shared/_header.html.erb
<div id="headerContainer">
  <div class="headerOuter">

    <div class="logo"><h1>Techs<strong>Place</strong></h1></div>

    <div class="clear"></div>
  </div>

</div>

app/views/shared/_menu.html.erb
<div class="clear"></div>
<div id="navContainer">
  <div class="navOuter">
    <div class="example">
      <ul id="nav">
        <li class="<%= action_name.eql?('index')? 'current': '' %>"><%= link_to 'Home', index_path %></li>
        <li><%= link_to 'Portfolio', "#" %></li>
        <li class="<%= action_name.eql?('about')? 'current': '' %>"><%= link_to 'About', about_path %></li>
        <li class="<%= action_name.eql?('new')? 'current': '' %>"><%= link_to 'Contact', new_contact_path %></li>
      </ul>
    </div>
    <div class="clear"></div>
  </div>

</div>

app/views/welcome/about.html.erb
<div class="clear"></div>
<div id="main_content">

  <div class="left_content">
    <h1>About Us</h1>
    <%= image_tag "icon_team.gif", alt: "", title: "", class: "left_img" %>
    <p class="about" align="justify">

      Techsplace is team of dedicated professionals experienced in the web space. We share the energy and enthusiasm towards shaping up the web image, be they individuals or corporate, small businesses or large enterprises. You can reinforce yourself through us and leverage our strengths in latest web 2.0 tools and technologies. From graphics to web design, web development to rich application development, product idea to implementation, component development to solution consulting, get the skills you want from our family of passionate engineers. We use latest web standards and educate our clients simultaneously. We give our best to make you look best on the web. <br />
    </p>
    <div class="clear"></div>
    <h1>What we do?</h1>
    <%= image_tag "icon_world.gif", alt: "", title: "", class: "left_img" %>
    <p class="about" align="justify">

      Rapid development and reduced time to market are primary goals for our client projects. We work with start-ups, product companies and agencies to develop web based applications. Our teams are set up to iterate quickly so we can push our client's products to market as soon as possible.<br/><br/>
      Unlike companies which provide "virtual teams" with little or no management, we have developed a team structure and process to ensure there is oversight and quality control on projects. Even if we assign one developer to your project, there is a Mentor and Engineering Director overseeing the work of the developer and measuring key metrics to ensure that the code we deliver adheres to the quality metrics we have defined. To learn more about the metrics we use and our process, please contact us for the white-paper. <br />
    </p>

  </div><!-- end of left content-->
</div>

app/views/welcome/index.html.erb
<div class="clear"></div>
<div id="bannerContainer">
  <div class="bannerOuter">
    <div id="slides-container" class="slides-container">
      <div id="slides">
        <div>
          <div class="slide-image"><%= image_tag 'image.jpg', alt: "Slide #1 image" %></div>
          <div class="slide-text">
            <h2>Slide #1</h2>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque venenatis sagittis enim. Maecenas ligula erat, egestas congue, varius nec, sagittis nec, purus. In neque.</p>
            <p class="frontpage-button">
              <a href="#">Lorem ipsum dolor</a>
            </p>


          </div>
        </div>

        <div class="centerButton">
          <%= image_tag "iphone.png" %>
          <div class="centerP">

            <h2>Have fun with slides!</h2>
            <p>These slides can contain anything a webpage can! HTML, Javascript, images, flash or whatever! They're completely easy to edit and add to as well, no need to bother editing or even going anywhere near some confusing Javascript files, simply add a &lt;div&gt;&lt;/div&gt; tag with your slider content to the "slides" contain - it takes just seconds to do!</p>

          </div>
        </div>

        <div>
          <div class="slide-image slide-image-right"><%= image_tag 'google_android.png', width: "350", height: "269", alt: "Slide #3 image" %></div>
          <div class="slide-text">
            <h2>Slide #3</h2>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque venenatis sagittis enim. Maecenas ligula erat, egestas congue, varius nec, sagittis nec, purus. In neque. Curabitur at metus tincidunt dui tristique molestie. Donec porta molestie tortor. Fusce euismod consectetuer sapien. Fusce ac velit.</p>


          </div>
        </div>
      </div>
      <div class="controls"><span class="jFlowNext"><span>Next</span></span><span class="jFlowPrev"><span>Prev</span></span></div>
      <div id="myController" class="hidden"><span class="jFlowControl">Slide 1</span><span class="jFlowControl">Slide 1</span><span class="jFlowControl">Slide 1</span></div>
    </div>


  </div>
  <div class="clear"></div>
</div>
<div class="clear"></div>
<div id="contentContainer">
  <div class="contentOuter">

    <div class="nav2">
      <ul>
        <li> <a href="#"><%= image_tag "Untitled-1.jpg", width: "290", height: "134" %></a>
          <h6>Intuitive Options Panel</h6>
          <p>TechsPlace features an amazingly powerful administration panel. The     extensive array of options combined with a familiar WordPress user     interface make it the most usable options panel you've ever experienced.</p>
          <div class="clear"></div>
          <a href="#" class="more">Learn More →</a> </li>

        <li> <a href="#"><%= image_tag "shortcodes.jpg", width: "290", height: "134" %></a>
          <h6>Powerful ShortCodes</h6>
          <p>TechsPlace comes packed with over 100 powerful shortcodes. Create     Multi-column layouts, Insert stylish buttons and Employ powerful     interface tabs, all from within a simple point-and-click shortcode     manager.</p>
          <div class="clear"></div>
          <a href="#" class="more">Learn More →</a> </li>
        <li style="margin-left:0px;"> <a href="#"><%= image_tag "image.jpg", width: "290", height: "134" %></a>
          <h6>Elegant Page Layouts</h6>
          <p>Vertical Navigation? Horizontal Navigation? Left Sidebar? Right     Sidebar? TechsPlace comes packed with a never ending array of 20 different     page layouts and the ability to create an unlimited amount of sidebars.</p>
          <div class="clear"></div>
          <a href="#" class="more">Learn More →</a> </li>
      </ul>
    </div>
    <div class="clear"></div>
  </div>
</div>